/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreTheyPlayingRouteImport } from './routes/are-they-playing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as FantasyLeadersRouteImport } from './routes/fantasy-leaders'
import { Route as FantasyPointsAllowedRouteImport } from './routes/fantasy-points-allowed'
import { Route as HofRouteImport } from './routes/hof'
import { Route as InjuryReportsRouteImport } from './routes/injury-reports'
import { Route as LeagueHqRouteImport } from './routes/league-hq'
import { Route as LeaguesyncRouteImport } from './routes/leaguesync'
import { Route as MRouteImport } from './routes/m'
import { Route as MatchupsGuideRouteImport } from './routes/matchups-guide'
import { Route as MockDraftRouteImport } from './routes/mock-draft'
import { Route as MostTargetedPlayersRouteImport } from './routes/most-targeted-players'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as RedZoneStatsRouteImport } from './routes/red-zone-stats'
import { Route as SeasonProjectionsRouteImport } from './routes/season-projections'
import { Route as SosAnalysisRouteImport } from './routes/sos-analysis'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as TheWireRouteImport } from './routes/the-wire'
import { Route as TopAvailableRouteImport } from './routes/top-available'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as TradeDeskRouteImport } from './routes/trade-desk'
import { Route as TradeMarketValuesRouteImport } from './routes/trade-market-values'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as WarRoomRouteImport } from './routes/war-room'
import { Route as WeeklyProjectionsRouteImport } from './routes/weekly-projections'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAdminRouteImport } from './routes/account.admin'
import { Route as AdminProjectionAnalyticsRouteImport } from './routes/admin.projection-analytics'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AuthConfirmedRouteImport } from './routes/auth_.confirmed'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as MSettingsRouteImport } from './routes/m.settings'
import { Route as MockDraftSetupRouteImport } from './routes/mock-draft_.setup'
import { Route as NflTeamNflIdRouteImport } from './routes/nfl-team.$nflId'
import { Route as PlaybookIndexRouteImport } from './routes/playbook.index'
import { Route as PlaybookMatchupRouteImport } from './routes/playbook.matchup'
import { Route as PlaybookMyTeamRouteImport } from './routes/playbook.my-team'
import { Route as PlaybookPressRoomRouteImport } from './routes/playbook.press-room'
import { Route as PlaybookRankingsRouteImport } from './routes/playbook.rankings'
import { Route as PlaybookRostersRouteImport } from './routes/playbook.rosters'
import { Route as PlaybookTransactionsRouteImport } from './routes/playbook.transactions'
import { Route as PlayerIdRouteImport } from './routes/player.$id'
import { Route as TeamTeamIdRouteImport } from './routes/team.$teamId'
import { Route as AccountLeaguesIndexRouteImport } from './routes/account.leagues.index'
import { Route as AccountLeaguesConnectionIdRouteImport } from './routes/account.leagues.$connectionId'
import { Route as AccountLeaguesNativeRouteImport } from './routes/account.leagues.native'
import { Route as ApiAdminSeedPlayerWarehouseRouteImport } from './routes/api/admin/seed-player-warehouse'
import { Route as ApiAdminTidbMigrateRouteImport } from './routes/api/admin/tidb-migrate'
import { Route as ApiCronLeagueDeltaSyncRouteImport } from './routes/api/cron/league-delta-sync'
import { Route as ApiCronLeaguePlanningSnapsRouteImport } from './routes/api/cron/league-planning-snaps'
import { Route as ApiCronResearchAggregatesRouteImport } from './routes/api/cron/research-aggregates'
import { Route as ApiCronWarehouseIngestRouteImport } from './routes/api/cron/warehouse-ingest'
import { Route as ApiDataPlayersRouteImport } from './routes/api/data/players'
import { Route as ApiDataPlayersExportRouteImport } from './routes/api/data/players-export'
import { Route as ApiPublicScoreboardRouteImport } from './routes/api/public/scoreboard'
import { Route as ApiWebhooksSyncRouteImport } from './routes/api/webhooks/sync'
import { Route as MLeagueLeagueIdRouteImport } from './routes/m.league.$leagueId'
import { Route as ApiAuthYahooCallbackRouteImport } from './routes/api/auth/yahoo/callback'
import { Route as ApiAuthYahooConnectRouteImport } from './routes/api/auth/yahoo/connect'
import { Route as ApiDataLeagueIdRouteImport } from './routes/api/data/league.$id'
import { Route as ApiDataPlayerIdRouteImport } from './routes/api/data/player.$id'
import { Route as ApiDataResearchKindRouteImport } from './routes/api/data/research.$kind'
import { Route as ApiDataSnapKindRouteImport } from './routes/api/data/snap.$kind'
import { Route as MLeagueLeagueIdIndexRouteImport } from './routes/m.league.$leagueId.index'
import { Route as MLeagueLeagueIdFeedRouteImport } from './routes/m.league.$leagueId.feed'
import { Route as MLeagueLeagueIdMatchupRouteImport } from './routes/m.league.$leagueId.matchup'
import { Route as MLeagueLeagueIdPlayersRouteImport } from './routes/m.league.$leagueId.players'
import { Route as MLeagueLeagueIdTeamRouteImport } from './routes/m.league.$leagueId.team'
import { Route as MLeagueLeagueIdTradesRouteImport } from './routes/m.league.$leagueId.trades'
import { Route as MLeagueLeagueIdWaiversRouteImport } from './routes/m.league.$leagueId.waivers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreTheyPlayingRoute = AreTheyPlayingRouteImport.update({
  id: '/are-they-playing',
  path: '/are-they-playing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyLeadersRoute = FantasyLeadersRouteImport.update({
  id: '/fantasy-leaders',
  path: '/fantasy-leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyPointsAllowedRoute = FantasyPointsAllowedRouteImport.update({
  id: '/fantasy-points-allowed',
  path: '/fantasy-points-allowed',
  getParentRoute: () => rootRouteImport,
} as any)
const HofRoute = HofRouteImport.update({
  id: '/hof',
  path: '/hof',
  getParentRoute: () => rootRouteImport,
} as any)
const InjuryReportsRoute = InjuryReportsRouteImport.update({
  id: '/injury-reports',
  path: '/injury-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueHqRoute = LeagueHqRouteImport.update({
  id: '/league-hq',
  path: '/league-hq',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesyncRoute = LeaguesyncRouteImport.update({
  id: '/leaguesync',
  path: '/leaguesync',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupsGuideRoute = MatchupsGuideRouteImport.update({
  id: '/matchups-guide',
  path: '/matchups-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MockDraftRoute = MockDraftRouteImport.update({
  id: '/mock-draft',
  path: '/mock-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const MostTargetedPlayersRoute = MostTargetedPlayersRouteImport.update({
  id: '/most-targeted-players',
  path: '/most-targeted-players',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const RedZoneStatsRoute = RedZoneStatsRouteImport.update({
  id: '/red-zone-stats',
  path: '/red-zone-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonProjectionsRoute = SeasonProjectionsRouteImport.update({
  id: '/season-projections',
  path: '/season-projections',
  getParentRoute: () => rootRouteImport,
} as any)
const SosAnalysisRoute = SosAnalysisRouteImport.update({
  id: '/sos-analysis',
  path: '/sos-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const TheWireRoute = TheWireRouteImport.update({
  id: '/the-wire',
  path: '/the-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const TopAvailableRoute = TopAvailableRouteImport.update({
  id: '/top-available',
  path: '/top-available',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeDeskRoute = TradeDeskRouteImport.update({
  id: '/trade-desk',
  path: '/trade-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeMarketValuesRoute = TradeMarketValuesRouteImport.update({
  id: '/trade-market-values',
  path: '/trade-market-values',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const WarRoomRoute = WarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyProjectionsRoute = WeeklyProjectionsRouteImport.update({
  id: '/weekly-projections',
  path: '/weekly-projections',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAdminRoute = AccountAdminRouteImport.update({
  id: '/account/admin',
  path: '/account/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectionAnalyticsRoute =
  AdminProjectionAnalyticsRouteImport.update({
    id: '/admin/projection-analytics',
    path: '/admin/projection-analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/auth_/confirmed',
  path: '/auth/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const MSettingsRoute = MSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MRoute,
} as any)
const MockDraftSetupRoute = MockDraftSetupRouteImport.update({
  id: '/mock-draft_/setup',
  path: '/mock-draft/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const NflTeamNflIdRoute = NflTeamNflIdRouteImport.update({
  id: '/nfl-team/$nflId',
  path: '/nfl-team/$nflId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookMatchupRoute = PlaybookMatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookMyTeamRoute = PlaybookMyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookPressRoomRoute = PlaybookPressRoomRouteImport.update({
  id: '/press-room',
  path: '/press-room',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookRankingsRoute = PlaybookRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookRostersRoute = PlaybookRostersRouteImport.update({
  id: '/rosters',
  path: '/rosters',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookTransactionsRoute = PlaybookTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamTeamIdRoute = TeamTeamIdRouteImport.update({
  id: '/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLeaguesIndexRoute = AccountLeaguesIndexRouteImport.update({
  id: '/account/leagues/',
  path: '/account/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLeaguesConnectionIdRoute =
  AccountLeaguesConnectionIdRouteImport.update({
    id: '/account/leagues/$connectionId',
    path: '/account/leagues/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountLeaguesNativeRoute = AccountLeaguesNativeRouteImport.update({
  id: '/account/leagues/native',
  path: '/account/leagues/native',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedPlayerWarehouseRoute =
  ApiAdminSeedPlayerWarehouseRouteImport.update({
    id: '/api/admin/seed-player-warehouse',
    path: '/api/admin/seed-player-warehouse',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminTidbMigrateRoute = ApiAdminTidbMigrateRouteImport.update({
  id: '/api/admin/tidb-migrate',
  path: '/api/admin/tidb-migrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronLeagueDeltaSyncRoute = ApiCronLeagueDeltaSyncRouteImport.update({
  id: '/api/cron/league-delta-sync',
  path: '/api/cron/league-delta-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronLeaguePlanningSnapsRoute =
  ApiCronLeaguePlanningSnapsRouteImport.update({
    id: '/api/cron/league-planning-snaps',
    path: '/api/cron/league-planning-snaps',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronResearchAggregatesRoute =
  ApiCronResearchAggregatesRouteImport.update({
    id: '/api/cron/research-aggregates',
    path: '/api/cron/research-aggregates',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronWarehouseIngestRoute = ApiCronWarehouseIngestRouteImport.update({
  id: '/api/cron/warehouse-ingest',
  path: '/api/cron/warehouse-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataPlayersRoute = ApiDataPlayersRouteImport.update({
  id: '/api/data/players',
  path: '/api/data/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataPlayersExportRoute = ApiDataPlayersExportRouteImport.update({
  id: '/api/data/players-export',
  path: '/api/data/players-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScoreboardRoute = ApiPublicScoreboardRouteImport.update({
  id: '/api/public/scoreboard',
  path: '/api/public/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksSyncRoute = ApiWebhooksSyncRouteImport.update({
  id: '/api/webhooks/sync',
  path: '/api/webhooks/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const MLeagueLeagueIdRoute = MLeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => MRoute,
} as any)
const ApiAuthYahooCallbackRoute = ApiAuthYahooCallbackRouteImport.update({
  id: '/api/auth/yahoo/callback',
  path: '/api/auth/yahoo/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthYahooConnectRoute = ApiAuthYahooConnectRouteImport.update({
  id: '/api/auth/yahoo/connect',
  path: '/api/auth/yahoo/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataLeagueIdRoute = ApiDataLeagueIdRouteImport.update({
  id: '/api/data/league/$id',
  path: '/api/data/league/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataPlayerIdRoute = ApiDataPlayerIdRouteImport.update({
  id: '/api/data/player/$id',
  path: '/api/data/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataResearchKindRoute = ApiDataResearchKindRouteImport.update({
  id: '/api/data/research/$kind',
  path: '/api/data/research/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataSnapKindRoute = ApiDataSnapKindRouteImport.update({
  id: '/api/data/snap/$kind',
  path: '/api/data/snap/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const MLeagueLeagueIdIndexRoute = MLeagueLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MLeagueLeagueIdRoute,
} as any)
const MLeagueLeagueIdFeedRoute = MLeagueLeagueIdFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => MLeagueLeagueIdRoute,
} as any)
const MLeagueLeagueIdMatchupRoute = MLeagueLeagueIdMatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => MLeagueLeagueIdRoute,
} as any)
const MLeagueLeagueIdPlayersRoute = MLeagueLeagueIdPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => MLeagueLeagueIdRoute,
} as any)
const MLeagueLeagueIdTeamRoute = MLeagueLeagueIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MLeagueLeagueIdRoute,
} as any)
const MLeagueLeagueIdTradesRoute = MLeagueLeagueIdTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => MLeagueLeagueIdRoute,
} as any)
const MLeagueLeagueIdWaiversRoute = MLeagueLeagueIdWaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => MLeagueLeagueIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/are-they-playing': typeof AreTheyPlayingRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/fantasy-leaders': typeof FantasyLeadersRoute
  '/fantasy-points-allowed': typeof FantasyPointsAllowedRoute
  '/hof': typeof HofRoute
  '/injury-reports': typeof InjuryReportsRoute
  '/league-hq': typeof LeagueHqRoute
  '/leaguesync': typeof LeaguesyncRoute
  '/m': typeof MRouteWithChildren
  '/matchups-guide': typeof MatchupsGuideRoute
  '/mock-draft': typeof MockDraftRoute
  '/most-targeted-players': typeof MostTargetedPlayersRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/red-zone-stats': typeof RedZoneStatsRoute
  '/season-projections': typeof SeasonProjectionsRoute
  '/sos-analysis': typeof SosAnalysisRoute
  '/standings': typeof StandingsRoute
  '/the-wire': typeof TheWireRoute
  '/top-available': typeof TopAvailableRoute
  '/trade': typeof TradeRoute
  '/trade-desk': typeof TradeDeskRoute
  '/trade-market-values': typeof TradeMarketValuesRoute
  '/waiver': typeof WaiverRoute
  '/war-room': typeof WarRoomRoute
  '/weekly-projections': typeof WeeklyProjectionsRoute
  '/account/admin': typeof AccountAdminRoute
  '/admin/projection-analytics': typeof AdminProjectionAnalyticsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/m/settings': typeof MSettingsRoute
  '/mock-draft/setup': typeof MockDraftSetupRoute
  '/nfl-team/$nflId': typeof NflTeamNflIdRoute
  '/playbook/matchup': typeof PlaybookMatchupRoute
  '/playbook/my-team': typeof PlaybookMyTeamRoute
  '/playbook/press-room': typeof PlaybookPressRoomRoute
  '/playbook/rankings': typeof PlaybookRankingsRoute
  '/playbook/rosters': typeof PlaybookRostersRoute
  '/playbook/transactions': typeof PlaybookTransactionsRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/account/': typeof AccountIndexRoute
  '/m/': typeof MIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/account/leagues/$connectionId': typeof AccountLeaguesConnectionIdRoute
  '/account/leagues/native': typeof AccountLeaguesNativeRoute
  '/api/admin/seed-player-warehouse': typeof ApiAdminSeedPlayerWarehouseRoute
  '/api/admin/tidb-migrate': typeof ApiAdminTidbMigrateRoute
  '/api/cron/league-delta-sync': typeof ApiCronLeagueDeltaSyncRoute
  '/api/cron/league-planning-snaps': typeof ApiCronLeaguePlanningSnapsRoute
  '/api/cron/research-aggregates': typeof ApiCronResearchAggregatesRoute
  '/api/cron/warehouse-ingest': typeof ApiCronWarehouseIngestRoute
  '/api/data/players': typeof ApiDataPlayersRoute
  '/api/data/players-export': typeof ApiDataPlayersExportRoute
  '/api/public/scoreboard': typeof ApiPublicScoreboardRoute
  '/api/webhooks/sync': typeof ApiWebhooksSyncRoute
  '/m/league/$leagueId': typeof MLeagueLeagueIdRouteWithChildren
  '/account/leagues/': typeof AccountLeaguesIndexRoute
  '/api/auth/yahoo/callback': typeof ApiAuthYahooCallbackRoute
  '/api/auth/yahoo/connect': typeof ApiAuthYahooConnectRoute
  '/api/data/league/$id': typeof ApiDataLeagueIdRoute
  '/api/data/player/$id': typeof ApiDataPlayerIdRoute
  '/api/data/research/$kind': typeof ApiDataResearchKindRoute
  '/api/data/snap/$kind': typeof ApiDataSnapKindRoute
  '/m/league/$leagueId/feed': typeof MLeagueLeagueIdFeedRoute
  '/m/league/$leagueId/matchup': typeof MLeagueLeagueIdMatchupRoute
  '/m/league/$leagueId/players': typeof MLeagueLeagueIdPlayersRoute
  '/m/league/$leagueId/team': typeof MLeagueLeagueIdTeamRoute
  '/m/league/$leagueId/trades': typeof MLeagueLeagueIdTradesRoute
  '/m/league/$leagueId/waivers': typeof MLeagueLeagueIdWaiversRoute
  '/m/league/$leagueId/': typeof MLeagueLeagueIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/are-they-playing': typeof AreTheyPlayingRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/fantasy-leaders': typeof FantasyLeadersRoute
  '/fantasy-points-allowed': typeof FantasyPointsAllowedRoute
  '/hof': typeof HofRoute
  '/injury-reports': typeof InjuryReportsRoute
  '/league-hq': typeof LeagueHqRoute
  '/leaguesync': typeof LeaguesyncRoute
  '/matchups-guide': typeof MatchupsGuideRoute
  '/mock-draft': typeof MockDraftRoute
  '/most-targeted-players': typeof MostTargetedPlayersRoute
  '/red-zone-stats': typeof RedZoneStatsRoute
  '/season-projections': typeof SeasonProjectionsRoute
  '/sos-analysis': typeof SosAnalysisRoute
  '/standings': typeof StandingsRoute
  '/the-wire': typeof TheWireRoute
  '/top-available': typeof TopAvailableRoute
  '/trade': typeof TradeRoute
  '/trade-desk': typeof TradeDeskRoute
  '/trade-market-values': typeof TradeMarketValuesRoute
  '/waiver': typeof WaiverRoute
  '/war-room': typeof WarRoomRoute
  '/weekly-projections': typeof WeeklyProjectionsRoute
  '/account/admin': typeof AccountAdminRoute
  '/admin/projection-analytics': typeof AdminProjectionAnalyticsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/m/settings': typeof MSettingsRoute
  '/mock-draft/setup': typeof MockDraftSetupRoute
  '/nfl-team/$nflId': typeof NflTeamNflIdRoute
  '/playbook/matchup': typeof PlaybookMatchupRoute
  '/playbook/my-team': typeof PlaybookMyTeamRoute
  '/playbook/press-room': typeof PlaybookPressRoomRoute
  '/playbook/rankings': typeof PlaybookRankingsRoute
  '/playbook/rosters': typeof PlaybookRostersRoute
  '/playbook/transactions': typeof PlaybookTransactionsRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/account': typeof AccountIndexRoute
  '/m': typeof MIndexRoute
  '/playbook': typeof PlaybookIndexRoute
  '/account/leagues/$connectionId': typeof AccountLeaguesConnectionIdRoute
  '/account/leagues/native': typeof AccountLeaguesNativeRoute
  '/api/admin/seed-player-warehouse': typeof ApiAdminSeedPlayerWarehouseRoute
  '/api/admin/tidb-migrate': typeof ApiAdminTidbMigrateRoute
  '/api/cron/league-delta-sync': typeof ApiCronLeagueDeltaSyncRoute
  '/api/cron/league-planning-snaps': typeof ApiCronLeaguePlanningSnapsRoute
  '/api/cron/research-aggregates': typeof ApiCronResearchAggregatesRoute
  '/api/cron/warehouse-ingest': typeof ApiCronWarehouseIngestRoute
  '/api/data/players': typeof ApiDataPlayersRoute
  '/api/data/players-export': typeof ApiDataPlayersExportRoute
  '/api/public/scoreboard': typeof ApiPublicScoreboardRoute
  '/api/webhooks/sync': typeof ApiWebhooksSyncRoute
  '/account/leagues': typeof AccountLeaguesIndexRoute
  '/api/auth/yahoo/callback': typeof ApiAuthYahooCallbackRoute
  '/api/auth/yahoo/connect': typeof ApiAuthYahooConnectRoute
  '/api/data/league/$id': typeof ApiDataLeagueIdRoute
  '/api/data/player/$id': typeof ApiDataPlayerIdRoute
  '/api/data/research/$kind': typeof ApiDataResearchKindRoute
  '/api/data/snap/$kind': typeof ApiDataSnapKindRoute
  '/m/league/$leagueId/feed': typeof MLeagueLeagueIdFeedRoute
  '/m/league/$leagueId/matchup': typeof MLeagueLeagueIdMatchupRoute
  '/m/league/$leagueId/players': typeof MLeagueLeagueIdPlayersRoute
  '/m/league/$leagueId/team': typeof MLeagueLeagueIdTeamRoute
  '/m/league/$leagueId/trades': typeof MLeagueLeagueIdTradesRoute
  '/m/league/$leagueId/waivers': typeof MLeagueLeagueIdWaiversRoute
  '/m/league/$leagueId': typeof MLeagueLeagueIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/are-they-playing': typeof AreTheyPlayingRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/fantasy-leaders': typeof FantasyLeadersRoute
  '/fantasy-points-allowed': typeof FantasyPointsAllowedRoute
  '/hof': typeof HofRoute
  '/injury-reports': typeof InjuryReportsRoute
  '/league-hq': typeof LeagueHqRoute
  '/leaguesync': typeof LeaguesyncRoute
  '/m': typeof MRouteWithChildren
  '/matchups-guide': typeof MatchupsGuideRoute
  '/mock-draft': typeof MockDraftRoute
  '/most-targeted-players': typeof MostTargetedPlayersRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/red-zone-stats': typeof RedZoneStatsRoute
  '/season-projections': typeof SeasonProjectionsRoute
  '/sos-analysis': typeof SosAnalysisRoute
  '/standings': typeof StandingsRoute
  '/the-wire': typeof TheWireRoute
  '/top-available': typeof TopAvailableRoute
  '/trade': typeof TradeRoute
  '/trade-desk': typeof TradeDeskRoute
  '/trade-market-values': typeof TradeMarketValuesRoute
  '/waiver': typeof WaiverRoute
  '/war-room': typeof WarRoomRoute
  '/weekly-projections': typeof WeeklyProjectionsRoute
  '/account/admin': typeof AccountAdminRoute
  '/admin/projection-analytics': typeof AdminProjectionAnalyticsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/auth_/confirmed': typeof AuthConfirmedRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
  '/m/settings': typeof MSettingsRoute
  '/mock-draft_/setup': typeof MockDraftSetupRoute
  '/nfl-team/$nflId': typeof NflTeamNflIdRoute
  '/playbook/matchup': typeof PlaybookMatchupRoute
  '/playbook/my-team': typeof PlaybookMyTeamRoute
  '/playbook/press-room': typeof PlaybookPressRoomRoute
  '/playbook/rankings': typeof PlaybookRankingsRoute
  '/playbook/rosters': typeof PlaybookRostersRoute
  '/playbook/transactions': typeof PlaybookTransactionsRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$teamId': typeof TeamTeamIdRoute
  '/account/': typeof AccountIndexRoute
  '/m/': typeof MIndexRoute
  '/playbook/': typeof PlaybookIndexRoute
  '/account/leagues/$connectionId': typeof AccountLeaguesConnectionIdRoute
  '/account/leagues/native': typeof AccountLeaguesNativeRoute
  '/api/admin/seed-player-warehouse': typeof ApiAdminSeedPlayerWarehouseRoute
  '/api/admin/tidb-migrate': typeof ApiAdminTidbMigrateRoute
  '/api/cron/league-delta-sync': typeof ApiCronLeagueDeltaSyncRoute
  '/api/cron/league-planning-snaps': typeof ApiCronLeaguePlanningSnapsRoute
  '/api/cron/research-aggregates': typeof ApiCronResearchAggregatesRoute
  '/api/cron/warehouse-ingest': typeof ApiCronWarehouseIngestRoute
  '/api/data/players': typeof ApiDataPlayersRoute
  '/api/data/players-export': typeof ApiDataPlayersExportRoute
  '/api/public/scoreboard': typeof ApiPublicScoreboardRoute
  '/api/webhooks/sync': typeof ApiWebhooksSyncRoute
  '/m/league/$leagueId': typeof MLeagueLeagueIdRouteWithChildren
  '/account/leagues/': typeof AccountLeaguesIndexRoute
  '/api/auth/yahoo/callback': typeof ApiAuthYahooCallbackRoute
  '/api/auth/yahoo/connect': typeof ApiAuthYahooConnectRoute
  '/api/data/league/$id': typeof ApiDataLeagueIdRoute
  '/api/data/player/$id': typeof ApiDataPlayerIdRoute
  '/api/data/research/$kind': typeof ApiDataResearchKindRoute
  '/api/data/snap/$kind': typeof ApiDataSnapKindRoute
  '/m/league/$leagueId/feed': typeof MLeagueLeagueIdFeedRoute
  '/m/league/$leagueId/matchup': typeof MLeagueLeagueIdMatchupRoute
  '/m/league/$leagueId/players': typeof MLeagueLeagueIdPlayersRoute
  '/m/league/$leagueId/team': typeof MLeagueLeagueIdTeamRoute
  '/m/league/$leagueId/trades': typeof MLeagueLeagueIdTradesRoute
  '/m/league/$leagueId/waivers': typeof MLeagueLeagueIdWaiversRoute
  '/m/league/$leagueId/': typeof MLeagueLeagueIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/are-they-playing'
    | '/auth'
    | '/draft'
    | '/fantasy-leaders'
    | '/fantasy-points-allowed'
    | '/hof'
    | '/injury-reports'
    | '/league-hq'
    | '/leaguesync'
    | '/m'
    | '/matchups-guide'
    | '/mock-draft'
    | '/most-targeted-players'
    | '/playbook'
    | '/red-zone-stats'
    | '/season-projections'
    | '/sos-analysis'
    | '/standings'
    | '/the-wire'
    | '/top-available'
    | '/trade'
    | '/trade-desk'
    | '/trade-market-values'
    | '/waiver'
    | '/war-room'
    | '/weekly-projections'
    | '/account/admin'
    | '/admin/projection-analytics'
    | '/articles/$slug'
    | '/auth/confirmed'
    | '/auth/reset-password'
    | '/m/settings'
    | '/mock-draft/setup'
    | '/nfl-team/$nflId'
    | '/playbook/matchup'
    | '/playbook/my-team'
    | '/playbook/press-room'
    | '/playbook/rankings'
    | '/playbook/rosters'
    | '/playbook/transactions'
    | '/player/$id'
    | '/team/$teamId'
    | '/account/'
    | '/m/'
    | '/playbook/'
    | '/account/leagues/$connectionId'
    | '/account/leagues/native'
    | '/api/admin/seed-player-warehouse'
    | '/api/admin/tidb-migrate'
    | '/api/cron/league-delta-sync'
    | '/api/cron/league-planning-snaps'
    | '/api/cron/research-aggregates'
    | '/api/cron/warehouse-ingest'
    | '/api/data/players'
    | '/api/data/players-export'
    | '/api/public/scoreboard'
    | '/api/webhooks/sync'
    | '/m/league/$leagueId'
    | '/account/leagues/'
    | '/api/auth/yahoo/callback'
    | '/api/auth/yahoo/connect'
    | '/api/data/league/$id'
    | '/api/data/player/$id'
    | '/api/data/research/$kind'
    | '/api/data/snap/$kind'
    | '/m/league/$leagueId/feed'
    | '/m/league/$leagueId/matchup'
    | '/m/league/$leagueId/players'
    | '/m/league/$leagueId/team'
    | '/m/league/$leagueId/trades'
    | '/m/league/$leagueId/waivers'
    | '/m/league/$leagueId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/are-they-playing'
    | '/auth'
    | '/draft'
    | '/fantasy-leaders'
    | '/fantasy-points-allowed'
    | '/hof'
    | '/injury-reports'
    | '/league-hq'
    | '/leaguesync'
    | '/matchups-guide'
    | '/mock-draft'
    | '/most-targeted-players'
    | '/red-zone-stats'
    | '/season-projections'
    | '/sos-analysis'
    | '/standings'
    | '/the-wire'
    | '/top-available'
    | '/trade'
    | '/trade-desk'
    | '/trade-market-values'
    | '/waiver'
    | '/war-room'
    | '/weekly-projections'
    | '/account/admin'
    | '/admin/projection-analytics'
    | '/articles/$slug'
    | '/auth/confirmed'
    | '/auth/reset-password'
    | '/m/settings'
    | '/mock-draft/setup'
    | '/nfl-team/$nflId'
    | '/playbook/matchup'
    | '/playbook/my-team'
    | '/playbook/press-room'
    | '/playbook/rankings'
    | '/playbook/rosters'
    | '/playbook/transactions'
    | '/player/$id'
    | '/team/$teamId'
    | '/account'
    | '/m'
    | '/playbook'
    | '/account/leagues/$connectionId'
    | '/account/leagues/native'
    | '/api/admin/seed-player-warehouse'
    | '/api/admin/tidb-migrate'
    | '/api/cron/league-delta-sync'
    | '/api/cron/league-planning-snaps'
    | '/api/cron/research-aggregates'
    | '/api/cron/warehouse-ingest'
    | '/api/data/players'
    | '/api/data/players-export'
    | '/api/public/scoreboard'
    | '/api/webhooks/sync'
    | '/account/leagues'
    | '/api/auth/yahoo/callback'
    | '/api/auth/yahoo/connect'
    | '/api/data/league/$id'
    | '/api/data/player/$id'
    | '/api/data/research/$kind'
    | '/api/data/snap/$kind'
    | '/m/league/$leagueId/feed'
    | '/m/league/$leagueId/matchup'
    | '/m/league/$leagueId/players'
    | '/m/league/$leagueId/team'
    | '/m/league/$leagueId/trades'
    | '/m/league/$leagueId/waivers'
    | '/m/league/$leagueId'
  id:
    | '__root__'
    | '/'
    | '/are-they-playing'
    | '/auth'
    | '/draft'
    | '/fantasy-leaders'
    | '/fantasy-points-allowed'
    | '/hof'
    | '/injury-reports'
    | '/league-hq'
    | '/leaguesync'
    | '/m'
    | '/matchups-guide'
    | '/mock-draft'
    | '/most-targeted-players'
    | '/playbook'
    | '/red-zone-stats'
    | '/season-projections'
    | '/sos-analysis'
    | '/standings'
    | '/the-wire'
    | '/top-available'
    | '/trade'
    | '/trade-desk'
    | '/trade-market-values'
    | '/waiver'
    | '/war-room'
    | '/weekly-projections'
    | '/account/admin'
    | '/admin/projection-analytics'
    | '/articles/$slug'
    | '/auth_/confirmed'
    | '/auth_/reset-password'
    | '/m/settings'
    | '/mock-draft_/setup'
    | '/nfl-team/$nflId'
    | '/playbook/matchup'
    | '/playbook/my-team'
    | '/playbook/press-room'
    | '/playbook/rankings'
    | '/playbook/rosters'
    | '/playbook/transactions'
    | '/player/$id'
    | '/team/$teamId'
    | '/account/'
    | '/m/'
    | '/playbook/'
    | '/account/leagues/$connectionId'
    | '/account/leagues/native'
    | '/api/admin/seed-player-warehouse'
    | '/api/admin/tidb-migrate'
    | '/api/cron/league-delta-sync'
    | '/api/cron/league-planning-snaps'
    | '/api/cron/research-aggregates'
    | '/api/cron/warehouse-ingest'
    | '/api/data/players'
    | '/api/data/players-export'
    | '/api/public/scoreboard'
    | '/api/webhooks/sync'
    | '/m/league/$leagueId'
    | '/account/leagues/'
    | '/api/auth/yahoo/callback'
    | '/api/auth/yahoo/connect'
    | '/api/data/league/$id'
    | '/api/data/player/$id'
    | '/api/data/research/$kind'
    | '/api/data/snap/$kind'
    | '/m/league/$leagueId/feed'
    | '/m/league/$leagueId/matchup'
    | '/m/league/$leagueId/players'
    | '/m/league/$leagueId/team'
    | '/m/league/$leagueId/trades'
    | '/m/league/$leagueId/waivers'
    | '/m/league/$leagueId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreTheyPlayingRoute: typeof AreTheyPlayingRoute
  AuthRoute: typeof AuthRoute
  DraftRoute: typeof DraftRoute
  FantasyLeadersRoute: typeof FantasyLeadersRoute
  FantasyPointsAllowedRoute: typeof FantasyPointsAllowedRoute
  HofRoute: typeof HofRoute
  InjuryReportsRoute: typeof InjuryReportsRoute
  LeagueHqRoute: typeof LeagueHqRoute
  LeaguesyncRoute: typeof LeaguesyncRoute
  MRoute: typeof MRouteWithChildren
  MatchupsGuideRoute: typeof MatchupsGuideRoute
  MockDraftRoute: typeof MockDraftRoute
  MostTargetedPlayersRoute: typeof MostTargetedPlayersRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  RedZoneStatsRoute: typeof RedZoneStatsRoute
  SeasonProjectionsRoute: typeof SeasonProjectionsRoute
  SosAnalysisRoute: typeof SosAnalysisRoute
  StandingsRoute: typeof StandingsRoute
  TheWireRoute: typeof TheWireRoute
  TopAvailableRoute: typeof TopAvailableRoute
  TradeRoute: typeof TradeRoute
  TradeDeskRoute: typeof TradeDeskRoute
  TradeMarketValuesRoute: typeof TradeMarketValuesRoute
  WaiverRoute: typeof WaiverRoute
  WarRoomRoute: typeof WarRoomRoute
  WeeklyProjectionsRoute: typeof WeeklyProjectionsRoute
  AccountAdminRoute: typeof AccountAdminRoute
  AdminProjectionAnalyticsRoute: typeof AdminProjectionAnalyticsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  AuthConfirmedRoute: typeof AuthConfirmedRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  MockDraftSetupRoute: typeof MockDraftSetupRoute
  NflTeamNflIdRoute: typeof NflTeamNflIdRoute
  PlayerIdRoute: typeof PlayerIdRoute
  TeamTeamIdRoute: typeof TeamTeamIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountLeaguesConnectionIdRoute: typeof AccountLeaguesConnectionIdRoute
  AccountLeaguesNativeRoute: typeof AccountLeaguesNativeRoute
  ApiAdminSeedPlayerWarehouseRoute: typeof ApiAdminSeedPlayerWarehouseRoute
  ApiAdminTidbMigrateRoute: typeof ApiAdminTidbMigrateRoute
  ApiCronLeagueDeltaSyncRoute: typeof ApiCronLeagueDeltaSyncRoute
  ApiCronLeaguePlanningSnapsRoute: typeof ApiCronLeaguePlanningSnapsRoute
  ApiCronResearchAggregatesRoute: typeof ApiCronResearchAggregatesRoute
  ApiCronWarehouseIngestRoute: typeof ApiCronWarehouseIngestRoute
  ApiDataPlayersRoute: typeof ApiDataPlayersRoute
  ApiDataPlayersExportRoute: typeof ApiDataPlayersExportRoute
  ApiPublicScoreboardRoute: typeof ApiPublicScoreboardRoute
  ApiWebhooksSyncRoute: typeof ApiWebhooksSyncRoute
  AccountLeaguesIndexRoute: typeof AccountLeaguesIndexRoute
  ApiAuthYahooCallbackRoute: typeof ApiAuthYahooCallbackRoute
  ApiAuthYahooConnectRoute: typeof ApiAuthYahooConnectRoute
  ApiDataLeagueIdRoute: typeof ApiDataLeagueIdRoute
  ApiDataPlayerIdRoute: typeof ApiDataPlayerIdRoute
  ApiDataResearchKindRoute: typeof ApiDataResearchKindRoute
  ApiDataSnapKindRoute: typeof ApiDataSnapKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/are-they-playing': {
      id: '/are-they-playing'
      path: '/are-they-playing'
      fullPath: '/are-they-playing'
      preLoaderRoute: typeof AreTheyPlayingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy-leaders': {
      id: '/fantasy-leaders'
      path: '/fantasy-leaders'
      fullPath: '/fantasy-leaders'
      preLoaderRoute: typeof FantasyLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy-points-allowed': {
      id: '/fantasy-points-allowed'
      path: '/fantasy-points-allowed'
      fullPath: '/fantasy-points-allowed'
      preLoaderRoute: typeof FantasyPointsAllowedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hof': {
      id: '/hof'
      path: '/hof'
      fullPath: '/hof'
      preLoaderRoute: typeof HofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/injury-reports': {
      id: '/injury-reports'
      path: '/injury-reports'
      fullPath: '/injury-reports'
      preLoaderRoute: typeof InjuryReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league-hq': {
      id: '/league-hq'
      path: '/league-hq'
      fullPath: '/league-hq'
      preLoaderRoute: typeof LeagueHqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaguesync': {
      id: '/leaguesync'
      path: '/leaguesync'
      fullPath: '/leaguesync'
      preLoaderRoute: typeof LeaguesyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchups-guide': {
      id: '/matchups-guide'
      path: '/matchups-guide'
      fullPath: '/matchups-guide'
      preLoaderRoute: typeof MatchupsGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-draft': {
      id: '/mock-draft'
      path: '/mock-draft'
      fullPath: '/mock-draft'
      preLoaderRoute: typeof MockDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/most-targeted-players': {
      id: '/most-targeted-players'
      path: '/most-targeted-players'
      fullPath: '/most-targeted-players'
      preLoaderRoute: typeof MostTargetedPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red-zone-stats': {
      id: '/red-zone-stats'
      path: '/red-zone-stats'
      fullPath: '/red-zone-stats'
      preLoaderRoute: typeof RedZoneStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/season-projections': {
      id: '/season-projections'
      path: '/season-projections'
      fullPath: '/season-projections'
      preLoaderRoute: typeof SeasonProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos-analysis': {
      id: '/sos-analysis'
      path: '/sos-analysis'
      fullPath: '/sos-analysis'
      preLoaderRoute: typeof SosAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-wire': {
      id: '/the-wire'
      path: '/the-wire'
      fullPath: '/the-wire'
      preLoaderRoute: typeof TheWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-available': {
      id: '/top-available'
      path: '/top-available'
      fullPath: '/top-available'
      preLoaderRoute: typeof TopAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-desk': {
      id: '/trade-desk'
      path: '/trade-desk'
      fullPath: '/trade-desk'
      preLoaderRoute: typeof TradeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-market-values': {
      id: '/trade-market-values'
      path: '/trade-market-values'
      fullPath: '/trade-market-values'
      preLoaderRoute: typeof TradeMarketValuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/war-room': {
      id: '/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof WarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-projections': {
      id: '/weekly-projections'
      path: '/weekly-projections'
      fullPath: '/weekly-projections'
      preLoaderRoute: typeof WeeklyProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/admin': {
      id: '/account/admin'
      path: '/account/admin'
      fullPath: '/account/admin'
      preLoaderRoute: typeof AccountAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projection-analytics': {
      id: '/admin/projection-analytics'
      path: '/admin/projection-analytics'
      fullPath: '/admin/projection-analytics'
      preLoaderRoute: typeof AdminProjectionAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/confirmed': {
      id: '/auth_/confirmed'
      path: '/auth/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/m/settings': {
      id: '/m/settings'
      path: '/settings'
      fullPath: '/m/settings'
      preLoaderRoute: typeof MSettingsRouteImport
      parentRoute: typeof MRoute
    }
    '/mock-draft_/setup': {
      id: '/mock-draft_/setup'
      path: '/mock-draft/setup'
      fullPath: '/mock-draft/setup'
      preLoaderRoute: typeof MockDraftSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfl-team/$nflId': {
      id: '/nfl-team/$nflId'
      path: '/nfl-team/$nflId'
      fullPath: '/nfl-team/$nflId'
      preLoaderRoute: typeof NflTeamNflIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/matchup': {
      id: '/playbook/matchup'
      path: '/matchup'
      fullPath: '/playbook/matchup'
      preLoaderRoute: typeof PlaybookMatchupRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/my-team': {
      id: '/playbook/my-team'
      path: '/my-team'
      fullPath: '/playbook/my-team'
      preLoaderRoute: typeof PlaybookMyTeamRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/press-room': {
      id: '/playbook/press-room'
      path: '/press-room'
      fullPath: '/playbook/press-room'
      preLoaderRoute: typeof PlaybookPressRoomRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/rankings': {
      id: '/playbook/rankings'
      path: '/rankings'
      fullPath: '/playbook/rankings'
      preLoaderRoute: typeof PlaybookRankingsRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/rosters': {
      id: '/playbook/rosters'
      path: '/rosters'
      fullPath: '/playbook/rosters'
      preLoaderRoute: typeof PlaybookRostersRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/transactions': {
      id: '/playbook/transactions'
      path: '/transactions'
      fullPath: '/playbook/transactions'
      preLoaderRoute: typeof PlaybookTransactionsRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$teamId': {
      id: '/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/team/$teamId'
      preLoaderRoute: typeof TeamTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/leagues/': {
      id: '/account/leagues/'
      path: '/account/leagues'
      fullPath: '/account/leagues/'
      preLoaderRoute: typeof AccountLeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/leagues/$connectionId': {
      id: '/account/leagues/$connectionId'
      path: '/account/leagues/$connectionId'
      fullPath: '/account/leagues/$connectionId'
      preLoaderRoute: typeof AccountLeaguesConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/leagues/native': {
      id: '/account/leagues/native'
      path: '/account/leagues/native'
      fullPath: '/account/leagues/native'
      preLoaderRoute: typeof AccountLeaguesNativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed-player-warehouse': {
      id: '/api/admin/seed-player-warehouse'
      path: '/api/admin/seed-player-warehouse'
      fullPath: '/api/admin/seed-player-warehouse'
      preLoaderRoute: typeof ApiAdminSeedPlayerWarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tidb-migrate': {
      id: '/api/admin/tidb-migrate'
      path: '/api/admin/tidb-migrate'
      fullPath: '/api/admin/tidb-migrate'
      preLoaderRoute: typeof ApiAdminTidbMigrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/league-delta-sync': {
      id: '/api/cron/league-delta-sync'
      path: '/api/cron/league-delta-sync'
      fullPath: '/api/cron/league-delta-sync'
      preLoaderRoute: typeof ApiCronLeagueDeltaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/league-planning-snaps': {
      id: '/api/cron/league-planning-snaps'
      path: '/api/cron/league-planning-snaps'
      fullPath: '/api/cron/league-planning-snaps'
      preLoaderRoute: typeof ApiCronLeaguePlanningSnapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/research-aggregates': {
      id: '/api/cron/research-aggregates'
      path: '/api/cron/research-aggregates'
      fullPath: '/api/cron/research-aggregates'
      preLoaderRoute: typeof ApiCronResearchAggregatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/warehouse-ingest': {
      id: '/api/cron/warehouse-ingest'
      path: '/api/cron/warehouse-ingest'
      fullPath: '/api/cron/warehouse-ingest'
      preLoaderRoute: typeof ApiCronWarehouseIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/players': {
      id: '/api/data/players'
      path: '/api/data/players'
      fullPath: '/api/data/players'
      preLoaderRoute: typeof ApiDataPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/players-export': {
      id: '/api/data/players-export'
      path: '/api/data/players-export'
      fullPath: '/api/data/players-export'
      preLoaderRoute: typeof ApiDataPlayersExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scoreboard': {
      id: '/api/public/scoreboard'
      path: '/api/public/scoreboard'
      fullPath: '/api/public/scoreboard'
      preLoaderRoute: typeof ApiPublicScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/sync': {
      id: '/api/webhooks/sync'
      path: '/api/webhooks/sync'
      fullPath: '/api/webhooks/sync'
      preLoaderRoute: typeof ApiWebhooksSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/league/$leagueId': {
      id: '/m/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/m/league/$leagueId'
      preLoaderRoute: typeof MLeagueLeagueIdRouteImport
      parentRoute: typeof MRoute
    }
    '/api/auth/yahoo/callback': {
      id: '/api/auth/yahoo/callback'
      path: '/api/auth/yahoo/callback'
      fullPath: '/api/auth/yahoo/callback'
      preLoaderRoute: typeof ApiAuthYahooCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/yahoo/connect': {
      id: '/api/auth/yahoo/connect'
      path: '/api/auth/yahoo/connect'
      fullPath: '/api/auth/yahoo/connect'
      preLoaderRoute: typeof ApiAuthYahooConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/league/$id': {
      id: '/api/data/league/$id'
      path: '/api/data/league/$id'
      fullPath: '/api/data/league/$id'
      preLoaderRoute: typeof ApiDataLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/player/$id': {
      id: '/api/data/player/$id'
      path: '/api/data/player/$id'
      fullPath: '/api/data/player/$id'
      preLoaderRoute: typeof ApiDataPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/research/$kind': {
      id: '/api/data/research/$kind'
      path: '/api/data/research/$kind'
      fullPath: '/api/data/research/$kind'
      preLoaderRoute: typeof ApiDataResearchKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data/snap/$kind': {
      id: '/api/data/snap/$kind'
      path: '/api/data/snap/$kind'
      fullPath: '/api/data/snap/$kind'
      preLoaderRoute: typeof ApiDataSnapKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/league/$leagueId/': {
      id: '/m/league/$leagueId/'
      path: '/'
      fullPath: '/m/league/$leagueId/'
      preLoaderRoute: typeof MLeagueLeagueIdIndexRouteImport
      parentRoute: typeof MLeagueLeagueIdRoute
    }
    '/m/league/$leagueId/feed': {
      id: '/m/league/$leagueId/feed'
      path: '/feed'
      fullPath: '/m/league/$leagueId/feed'
      preLoaderRoute: typeof MLeagueLeagueIdFeedRouteImport
      parentRoute: typeof MLeagueLeagueIdRoute
    }
    '/m/league/$leagueId/matchup': {
      id: '/m/league/$leagueId/matchup'
      path: '/matchup'
      fullPath: '/m/league/$leagueId/matchup'
      preLoaderRoute: typeof MLeagueLeagueIdMatchupRouteImport
      parentRoute: typeof MLeagueLeagueIdRoute
    }
    '/m/league/$leagueId/players': {
      id: '/m/league/$leagueId/players'
      path: '/players'
      fullPath: '/m/league/$leagueId/players'
      preLoaderRoute: typeof MLeagueLeagueIdPlayersRouteImport
      parentRoute: typeof MLeagueLeagueIdRoute
    }
    '/m/league/$leagueId/team': {
      id: '/m/league/$leagueId/team'
      path: '/team'
      fullPath: '/m/league/$leagueId/team'
      preLoaderRoute: typeof MLeagueLeagueIdTeamRouteImport
      parentRoute: typeof MLeagueLeagueIdRoute
    }
    '/m/league/$leagueId/trades': {
      id: '/m/league/$leagueId/trades'
      path: '/trades'
      fullPath: '/m/league/$leagueId/trades'
      preLoaderRoute: typeof MLeagueLeagueIdTradesRouteImport
      parentRoute: typeof MLeagueLeagueIdRoute
    }
    '/m/league/$leagueId/waivers': {
      id: '/m/league/$leagueId/waivers'
      path: '/waivers'
      fullPath: '/m/league/$leagueId/waivers'
      preLoaderRoute: typeof MLeagueLeagueIdWaiversRouteImport
      parentRoute: typeof MLeagueLeagueIdRoute
    }
  }
}

interface MLeagueLeagueIdRouteChildren {
  MLeagueLeagueIdFeedRoute: typeof MLeagueLeagueIdFeedRoute
  MLeagueLeagueIdMatchupRoute: typeof MLeagueLeagueIdMatchupRoute
  MLeagueLeagueIdPlayersRoute: typeof MLeagueLeagueIdPlayersRoute
  MLeagueLeagueIdTeamRoute: typeof MLeagueLeagueIdTeamRoute
  MLeagueLeagueIdTradesRoute: typeof MLeagueLeagueIdTradesRoute
  MLeagueLeagueIdWaiversRoute: typeof MLeagueLeagueIdWaiversRoute
  MLeagueLeagueIdIndexRoute: typeof MLeagueLeagueIdIndexRoute
}

const MLeagueLeagueIdRouteChildren: MLeagueLeagueIdRouteChildren = {
  MLeagueLeagueIdFeedRoute: MLeagueLeagueIdFeedRoute,
  MLeagueLeagueIdMatchupRoute: MLeagueLeagueIdMatchupRoute,
  MLeagueLeagueIdPlayersRoute: MLeagueLeagueIdPlayersRoute,
  MLeagueLeagueIdTeamRoute: MLeagueLeagueIdTeamRoute,
  MLeagueLeagueIdTradesRoute: MLeagueLeagueIdTradesRoute,
  MLeagueLeagueIdWaiversRoute: MLeagueLeagueIdWaiversRoute,
  MLeagueLeagueIdIndexRoute: MLeagueLeagueIdIndexRoute,
}

const MLeagueLeagueIdRouteWithChildren = MLeagueLeagueIdRoute._addFileChildren(
  MLeagueLeagueIdRouteChildren,
)

interface MRouteChildren {
  MSettingsRoute: typeof MSettingsRoute
  MIndexRoute: typeof MIndexRoute
  MLeagueLeagueIdRoute: typeof MLeagueLeagueIdRouteWithChildren
}

const MRouteChildren: MRouteChildren = {
  MSettingsRoute: MSettingsRoute,
  MIndexRoute: MIndexRoute,
  MLeagueLeagueIdRoute: MLeagueLeagueIdRouteWithChildren,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

interface PlaybookRouteChildren {
  PlaybookMatchupRoute: typeof PlaybookMatchupRoute
  PlaybookMyTeamRoute: typeof PlaybookMyTeamRoute
  PlaybookPressRoomRoute: typeof PlaybookPressRoomRoute
  PlaybookRankingsRoute: typeof PlaybookRankingsRoute
  PlaybookRostersRoute: typeof PlaybookRostersRoute
  PlaybookTransactionsRoute: typeof PlaybookTransactionsRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookMatchupRoute: PlaybookMatchupRoute,
  PlaybookMyTeamRoute: PlaybookMyTeamRoute,
  PlaybookPressRoomRoute: PlaybookPressRoomRoute,
  PlaybookRankingsRoute: PlaybookRankingsRoute,
  PlaybookRostersRoute: PlaybookRostersRoute,
  PlaybookTransactionsRoute: PlaybookTransactionsRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreTheyPlayingRoute: AreTheyPlayingRoute,
  AuthRoute: AuthRoute,
  DraftRoute: DraftRoute,
  FantasyLeadersRoute: FantasyLeadersRoute,
  FantasyPointsAllowedRoute: FantasyPointsAllowedRoute,
  HofRoute: HofRoute,
  InjuryReportsRoute: InjuryReportsRoute,
  LeagueHqRoute: LeagueHqRoute,
  LeaguesyncRoute: LeaguesyncRoute,
  MRoute: MRouteWithChildren,
  MatchupsGuideRoute: MatchupsGuideRoute,
  MockDraftRoute: MockDraftRoute,
  MostTargetedPlayersRoute: MostTargetedPlayersRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  RedZoneStatsRoute: RedZoneStatsRoute,
  SeasonProjectionsRoute: SeasonProjectionsRoute,
  SosAnalysisRoute: SosAnalysisRoute,
  StandingsRoute: StandingsRoute,
  TheWireRoute: TheWireRoute,
  TopAvailableRoute: TopAvailableRoute,
  TradeRoute: TradeRoute,
  TradeDeskRoute: TradeDeskRoute,
  TradeMarketValuesRoute: TradeMarketValuesRoute,
  WaiverRoute: WaiverRoute,
  WarRoomRoute: WarRoomRoute,
  WeeklyProjectionsRoute: WeeklyProjectionsRoute,
  AccountAdminRoute: AccountAdminRoute,
  AdminProjectionAnalyticsRoute: AdminProjectionAnalyticsRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  AuthConfirmedRoute: AuthConfirmedRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  MockDraftSetupRoute: MockDraftSetupRoute,
  NflTeamNflIdRoute: NflTeamNflIdRoute,
  PlayerIdRoute: PlayerIdRoute,
  TeamTeamIdRoute: TeamTeamIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountLeaguesConnectionIdRoute: AccountLeaguesConnectionIdRoute,
  AccountLeaguesNativeRoute: AccountLeaguesNativeRoute,
  ApiAdminSeedPlayerWarehouseRoute: ApiAdminSeedPlayerWarehouseRoute,
  ApiAdminTidbMigrateRoute: ApiAdminTidbMigrateRoute,
  ApiCronLeagueDeltaSyncRoute: ApiCronLeagueDeltaSyncRoute,
  ApiCronLeaguePlanningSnapsRoute: ApiCronLeaguePlanningSnapsRoute,
  ApiCronResearchAggregatesRoute: ApiCronResearchAggregatesRoute,
  ApiCronWarehouseIngestRoute: ApiCronWarehouseIngestRoute,
  ApiDataPlayersRoute: ApiDataPlayersRoute,
  ApiDataPlayersExportRoute: ApiDataPlayersExportRoute,
  ApiPublicScoreboardRoute: ApiPublicScoreboardRoute,
  ApiWebhooksSyncRoute: ApiWebhooksSyncRoute,
  AccountLeaguesIndexRoute: AccountLeaguesIndexRoute,
  ApiAuthYahooCallbackRoute: ApiAuthYahooCallbackRoute,
  ApiAuthYahooConnectRoute: ApiAuthYahooConnectRoute,
  ApiDataLeagueIdRoute: ApiDataLeagueIdRoute,
  ApiDataPlayerIdRoute: ApiDataPlayerIdRoute,
  ApiDataResearchKindRoute: ApiDataResearchKindRoute,
  ApiDataSnapKindRoute: ApiDataSnapKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
