/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as HofRouteImport } from './routes/hof'
import { Route as LeaguesyncRouteImport } from './routes/leaguesync'
import { Route as MockDraftRouteImport } from './routes/mock-draft'
import { Route as TheWireRouteImport } from './routes/the-wire'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as TradeDeskRouteImport } from './routes/trade-desk'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as WarRoomRouteImport } from './routes/war-room'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAdminRouteImport } from './routes/account.admin'
import { Route as AuthConfirmedRouteImport } from './routes/auth_.confirmed'
import { Route as MockDraftSetupRouteImport } from './routes/mock-draft_.setup'
import { Route as NflTeamNflIdRouteImport } from './routes/nfl-team.$nflId'
import { Route as PlayerIdRouteImport } from './routes/player.$id'
import { Route as AccountLeaguesIndexRouteImport } from './routes/account.leagues.index'
import { Route as AccountLeaguesConnectionIdRouteImport } from './routes/account.leagues.$connectionId'
import { Route as ApiPublicScoreboardRouteImport } from './routes/api/public/scoreboard'
import { Route as ApiAuthYahooCallbackRouteImport } from './routes/api/auth/yahoo/callback'
import { Route as ApiAuthYahooConnectRouteImport } from './routes/api/auth/yahoo/connect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const HofRoute = HofRouteImport.update({
  id: '/hof',
  path: '/hof',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesyncRoute = LeaguesyncRouteImport.update({
  id: '/leaguesync',
  path: '/leaguesync',
  getParentRoute: () => rootRouteImport,
} as any)
const MockDraftRoute = MockDraftRouteImport.update({
  id: '/mock-draft',
  path: '/mock-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const TheWireRoute = TheWireRouteImport.update({
  id: '/the-wire',
  path: '/the-wire',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeDeskRoute = TradeDeskRouteImport.update({
  id: '/trade-desk',
  path: '/trade-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const WarRoomRoute = WarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAdminRoute = AccountAdminRouteImport.update({
  id: '/account/admin',
  path: '/account/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/auth_/confirmed',
  path: '/auth/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const MockDraftSetupRoute = MockDraftSetupRouteImport.update({
  id: '/mock-draft_/setup',
  path: '/mock-draft/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const NflTeamNflIdRoute = NflTeamNflIdRouteImport.update({
  id: '/nfl-team/$nflId',
  path: '/nfl-team/$nflId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLeaguesIndexRoute = AccountLeaguesIndexRouteImport.update({
  id: '/account/leagues/',
  path: '/account/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLeaguesConnectionIdRoute =
  AccountLeaguesConnectionIdRouteImport.update({
    id: '/account/leagues/$connectionId',
    path: '/account/leagues/$connectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScoreboardRoute = ApiPublicScoreboardRouteImport.update({
  id: '/api/public/scoreboard',
  path: '/api/public/scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthYahooCallbackRoute = ApiAuthYahooCallbackRouteImport.update({
  id: '/api/auth/yahoo/callback',
  path: '/api/auth/yahoo/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthYahooConnectRoute = ApiAuthYahooConnectRouteImport.update({
  id: '/api/auth/yahoo/connect',
  path: '/api/auth/yahoo/connect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/hof': typeof HofRoute
  '/leaguesync': typeof LeaguesyncRoute
  '/mock-draft': typeof MockDraftRoute
  '/the-wire': typeof TheWireRoute
  '/trade': typeof TradeRoute
  '/trade-desk': typeof TradeDeskRoute
  '/waiver': typeof WaiverRoute
  '/war-room': typeof WarRoomRoute
  '/account/admin': typeof AccountAdminRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/mock-draft/setup': typeof MockDraftSetupRoute
  '/nfl-team/$nflId': typeof NflTeamNflIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/account/': typeof AccountIndexRoute
  '/account/leagues/$connectionId': typeof AccountLeaguesConnectionIdRoute
  '/api/public/scoreboard': typeof ApiPublicScoreboardRoute
  '/account/leagues/': typeof AccountLeaguesIndexRoute
  '/api/auth/yahoo/callback': typeof ApiAuthYahooCallbackRoute
  '/api/auth/yahoo/connect': typeof ApiAuthYahooConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/hof': typeof HofRoute
  '/leaguesync': typeof LeaguesyncRoute
  '/mock-draft': typeof MockDraftRoute
  '/the-wire': typeof TheWireRoute
  '/trade': typeof TradeRoute
  '/trade-desk': typeof TradeDeskRoute
  '/waiver': typeof WaiverRoute
  '/war-room': typeof WarRoomRoute
  '/account/admin': typeof AccountAdminRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/mock-draft/setup': typeof MockDraftSetupRoute
  '/nfl-team/$nflId': typeof NflTeamNflIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/account': typeof AccountIndexRoute
  '/account/leagues/$connectionId': typeof AccountLeaguesConnectionIdRoute
  '/api/public/scoreboard': typeof ApiPublicScoreboardRoute
  '/account/leagues': typeof AccountLeaguesIndexRoute
  '/api/auth/yahoo/callback': typeof ApiAuthYahooCallbackRoute
  '/api/auth/yahoo/connect': typeof ApiAuthYahooConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/draft': typeof DraftRoute
  '/hof': typeof HofRoute
  '/leaguesync': typeof LeaguesyncRoute
  '/mock-draft': typeof MockDraftRoute
  '/the-wire': typeof TheWireRoute
  '/trade': typeof TradeRoute
  '/trade-desk': typeof TradeDeskRoute
  '/waiver': typeof WaiverRoute
  '/war-room': typeof WarRoomRoute
  '/account/admin': typeof AccountAdminRoute
  '/auth_/confirmed': typeof AuthConfirmedRoute
  '/mock-draft_/setup': typeof MockDraftSetupRoute
  '/nfl-team/$nflId': typeof NflTeamNflIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/account/': typeof AccountIndexRoute
  '/account/leagues/$connectionId': typeof AccountLeaguesConnectionIdRoute
  '/api/public/scoreboard': typeof ApiPublicScoreboardRoute
  '/account/leagues/': typeof AccountLeaguesIndexRoute
  '/api/auth/yahoo/callback': typeof ApiAuthYahooCallbackRoute
  '/api/auth/yahoo/connect': typeof ApiAuthYahooConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/draft'
    | '/hof'
    | '/leaguesync'
    | '/mock-draft'
    | '/the-wire'
    | '/trade'
    | '/trade-desk'
    | '/waiver'
    | '/war-room'
    | '/account/admin'
    | '/auth/confirmed'
    | '/mock-draft/setup'
    | '/nfl-team/$nflId'
    | '/player/$id'
    | '/account/'
    | '/account/leagues/$connectionId'
    | '/api/public/scoreboard'
    | '/account/leagues/'
    | '/api/auth/yahoo/callback'
    | '/api/auth/yahoo/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/draft'
    | '/hof'
    | '/leaguesync'
    | '/mock-draft'
    | '/the-wire'
    | '/trade'
    | '/trade-desk'
    | '/waiver'
    | '/war-room'
    | '/account/admin'
    | '/auth/confirmed'
    | '/mock-draft/setup'
    | '/nfl-team/$nflId'
    | '/player/$id'
    | '/account'
    | '/account/leagues/$connectionId'
    | '/api/public/scoreboard'
    | '/account/leagues'
    | '/api/auth/yahoo/callback'
    | '/api/auth/yahoo/connect'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/draft'
    | '/hof'
    | '/leaguesync'
    | '/mock-draft'
    | '/the-wire'
    | '/trade'
    | '/trade-desk'
    | '/waiver'
    | '/war-room'
    | '/account/admin'
    | '/auth_/confirmed'
    | '/mock-draft_/setup'
    | '/nfl-team/$nflId'
    | '/player/$id'
    | '/account/'
    | '/account/leagues/$connectionId'
    | '/api/public/scoreboard'
    | '/account/leagues/'
    | '/api/auth/yahoo/callback'
    | '/api/auth/yahoo/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DraftRoute: typeof DraftRoute
  HofRoute: typeof HofRoute
  LeaguesyncRoute: typeof LeaguesyncRoute
  MockDraftRoute: typeof MockDraftRoute
  TheWireRoute: typeof TheWireRoute
  TradeRoute: typeof TradeRoute
  TradeDeskRoute: typeof TradeDeskRoute
  WaiverRoute: typeof WaiverRoute
  WarRoomRoute: typeof WarRoomRoute
  AccountAdminRoute: typeof AccountAdminRoute
  AuthConfirmedRoute: typeof AuthConfirmedRoute
  MockDraftSetupRoute: typeof MockDraftSetupRoute
  NflTeamNflIdRoute: typeof NflTeamNflIdRoute
  PlayerIdRoute: typeof PlayerIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountLeaguesConnectionIdRoute: typeof AccountLeaguesConnectionIdRoute
  ApiPublicScoreboardRoute: typeof ApiPublicScoreboardRoute
  AccountLeaguesIndexRoute: typeof AccountLeaguesIndexRoute
  ApiAuthYahooCallbackRoute: typeof ApiAuthYahooCallbackRoute
  ApiAuthYahooConnectRoute: typeof ApiAuthYahooConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hof': {
      id: '/hof'
      path: '/hof'
      fullPath: '/hof'
      preLoaderRoute: typeof HofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaguesync': {
      id: '/leaguesync'
      path: '/leaguesync'
      fullPath: '/leaguesync'
      preLoaderRoute: typeof LeaguesyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-draft': {
      id: '/mock-draft'
      path: '/mock-draft'
      fullPath: '/mock-draft'
      preLoaderRoute: typeof MockDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-wire': {
      id: '/the-wire'
      path: '/the-wire'
      fullPath: '/the-wire'
      preLoaderRoute: typeof TheWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-desk': {
      id: '/trade-desk'
      path: '/trade-desk'
      fullPath: '/trade-desk'
      preLoaderRoute: typeof TradeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/war-room': {
      id: '/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof WarRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/admin': {
      id: '/account/admin'
      path: '/account/admin'
      fullPath: '/account/admin'
      preLoaderRoute: typeof AccountAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/confirmed': {
      id: '/auth_/confirmed'
      path: '/auth/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-draft_/setup': {
      id: '/mock-draft_/setup'
      path: '/mock-draft/setup'
      fullPath: '/mock-draft/setup'
      preLoaderRoute: typeof MockDraftSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfl-team/$nflId': {
      id: '/nfl-team/$nflId'
      path: '/nfl-team/$nflId'
      fullPath: '/nfl-team/$nflId'
      preLoaderRoute: typeof NflTeamNflIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/leagues/': {
      id: '/account/leagues/'
      path: '/account/leagues'
      fullPath: '/account/leagues/'
      preLoaderRoute: typeof AccountLeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/leagues/$connectionId': {
      id: '/account/leagues/$connectionId'
      path: '/account/leagues/$connectionId'
      fullPath: '/account/leagues/$connectionId'
      preLoaderRoute: typeof AccountLeaguesConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scoreboard': {
      id: '/api/public/scoreboard'
      path: '/api/public/scoreboard'
      fullPath: '/api/public/scoreboard'
      preLoaderRoute: typeof ApiPublicScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/yahoo/callback': {
      id: '/api/auth/yahoo/callback'
      path: '/api/auth/yahoo/callback'
      fullPath: '/api/auth/yahoo/callback'
      preLoaderRoute: typeof ApiAuthYahooCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/yahoo/connect': {
      id: '/api/auth/yahoo/connect'
      path: '/api/auth/yahoo/connect'
      fullPath: '/api/auth/yahoo/connect'
      preLoaderRoute: typeof ApiAuthYahooConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DraftRoute: DraftRoute,
  HofRoute: HofRoute,
  LeaguesyncRoute: LeaguesyncRoute,
  MockDraftRoute: MockDraftRoute,
  TheWireRoute: TheWireRoute,
  TradeRoute: TradeRoute,
  TradeDeskRoute: TradeDeskRoute,
  WaiverRoute: WaiverRoute,
  WarRoomRoute: WarRoomRoute,
  AccountAdminRoute: AccountAdminRoute,
  AuthConfirmedRoute: AuthConfirmedRoute,
  MockDraftSetupRoute: MockDraftSetupRoute,
  NflTeamNflIdRoute: NflTeamNflIdRoute,
  PlayerIdRoute: PlayerIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountLeaguesConnectionIdRoute: AccountLeaguesConnectionIdRoute,
  ApiPublicScoreboardRoute: ApiPublicScoreboardRoute,
  AccountLeaguesIndexRoute: AccountLeaguesIndexRoute,
  ApiAuthYahooCallbackRoute: ApiAuthYahooCallbackRoute,
  ApiAuthYahooConnectRoute: ApiAuthYahooConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
