// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sweadgqmpeknifmoxgvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3ZWFkZ3FtcGVrbmlmbW94Z3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwODM5NzAsImV4cCI6MjEwMjY1OTk3MH0.p_hrFRkCRAsZhqc-n41d2UIK7o9IML_VIBm9LneVWb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});